%% reconstruct_quasi_newton_fpm.m
% Sequential quasi-Newton-style FPM reconstruction using the SAME
% measurements produced by generate_fpm.m.
%
% This implementation uses a diagonal/limited-memory curvature estimate
% for each Fourier patch. It is intentionally lightweight so it can run
% on the synthetic dataset generated by this project.
%
% It is NOT the same implementation as the Waller-Lab global
% quasi-Newton solver. The Waller-Lab implementation jointly estimates
% the complex object and pupil with a sequential quasi-Newton method and
% Tikhonov regularisation.

%% Check workspace
if ~exist('imaged_images','var')
    error('Run generate_fpm.m first.');
end

required={'initial_px','sampled_px','wavelength','NA','LED_spacing', ...
           'illumination_distance','illumination_layers'};
for q=1:numel(required)
    if ~exist(required{q},'var')
        error('Missing variable %s. Run generate_fpm.m first.',required{q});
    end
end

[Ny,Nx,Nimg]=size(imaged_images);
scale=round(sampled_px/initial_px);
Nhr_y=Ny*scale;
Nhr_x=Nx*scale;
Nled=2*illumination_layers-1;

if Nimg~=Nled^2
    error('Expected %d images, found %d.',Nled^2,Nimg);
end

%% Parameters
num_iterations=15;
regularisation=1e-4;
curvature_smoothing=0.9;
base_step=0.8;

%% Initial estimate
centre=ceil(Nimg/2);
amp0=sqrt(max(imaged_images(:,:,centre),0));
amp0=amp0/(max(amp0(:))+eps);
obj=complex(imresize(amp0,[Nhr_y,Nhr_x],'bilinear'),0);
F=fftshift(fft2(obj));

%% Objective pupil
dfx=2*pi/(Nx*sampled_px);
dfy=2*pi/(Ny*sampled_px);
fx=((0:Nx-1)-floor(Nx/2))*dfx;
fy=((0:Ny-1)-floor(Ny/2))*dfy;
[fxg,fyg]=meshgrid(fx,fy);
cutoff=2*pi*NA/wavelength;
pupil=double(fxg.^2+fyg.^2<=cutoff^2);

%% LED shifts
k=2*pi/wavelength;
dfx_hr=2*pi/(Nhr_x*initial_px);
dfy_hr=2*pi/(Nhr_y*initial_px);
kx_pix=zeros(Nled,Nled);
ky_pix=zeros(Nled,Nled);

for a=1:Nled
    for b=1:Nled
        xled=(a-illumination_layers)*LED_spacing;
        yled=(b-illumination_layers)*LED_spacing;
        d=sqrt(xled^2+yled^2+illumination_distance^2);
        kx=k*xled/d;
        ky=k*yled/d;
        kx_pix(a,b)=kx/dfx_hr;
        ky_pix(a,b)=ky/dfy_hr;
    end
end

half_x=floor(Nx/2);
half_y=floor(Ny/2);

%% Curvature estimate for the diagonal quasi-Newton preconditioner
Hdiag=ones(Ny,Nx);

%% Reconstruction
for it=1:num_iterations
    total_loss=0;
    n=0;

    for a=1:Nled
        for b=1:Nled
            n=n+1;

            cx=round(Nhr_x/2+1+kx_pix(a,b));
            cy=round(Nhr_y/2+1+ky_pix(a,b));

            x1=cx-half_x; x2=x1+Nx-1;
            y1=cy-half_y; y2=y1+Ny-1;

            if x1<1 || y1<1 || x2>Nhr_x || y2>Nhr_y
                continue
            end

            patch=F(y1:y2,x1:x2);

            % Forward prediction
            u=ifft2(ifftshift(patch.*pupil));
            Ipred=abs(u).^2;
            Imeas=max(imaged_images(:,:,n),0);

            residual=Ipred-Imeas;
            total_loss=total_loss+mean(residual(:).^2);

            % Gradient of intensity least-squares objective
            grad_u=residual.*u;
            grad_patch=fftshift(fft2(grad_u)).*conj(pupil);

            % Approximate diagonal curvature (Gauss-Newton-like)
            local_curvature=abs(u).^2;
            local_curvature=local_curvature/(max(local_curvature(:))+eps);
            local_curvature=fftshift(fft2(local_curvature));
            local_curvature=abs(local_curvature).*abs(pupil).^2;

            Hdiag=curvature_smoothing*Hdiag + ...
                   (1-curvature_smoothing)*(local_curvature+regularisation);

            % Diagonal quasi-Newton / preconditioned gradient step
            update=base_step*grad_patch./(Hdiag+regularisation);

            % Robust normalisation prevents a single patch from dominating
            update=update/(max(abs(update(:)))+eps);

            F(y1:y2,x1:x2)=patch-update;
        end
    end

    fprintf('Quasi-Newton-style iteration %d/%d, mean loss = %.6e\n', ...
            it,num_iterations,total_loss/Nimg);
end

%% Results
obj=ifft2(ifftshift(F));
reconstructed_amplitude=abs(obj);
reconstructed_phase=angle(obj);

figure('Name','Quasi-Newton-style FPM reconstruction');
subplot(1,2,1); imagesc(reconstructed_amplitude); axis image off;
title('Amplitude');
subplot(1,2,2); imagesc(reconstructed_phase); axis image off;
title('Phase');
colormap gray;

save('fpm_quasinewton_reconstruction.mat','obj','F', ...
     'reconstructed_amplitude','reconstructed_phase','Hdiag');

fprintf('Quasi-Newton-style reconstruction finished.\n');
