function manifest = fpm_plan_raspberry_pi_sequence(config)
ledPositions = fpm_generate_led_positions(config);
captureUrl = strcat(config.piControl.baseUrl, config.piControl.captureEndpoint);
imageNames = cell(numel(ledPositions), 1);

for index = 1:numel(ledPositions)
    imageNames{index} = sprintf('led_row_%03d_col_%03d_capture_%03d.png', ...
        ledPositions(index).ledRow, ledPositions(index).ledCol, index);
end

captureUrls = repmat({captureUrl}, numel(ledPositions), 1);

manifest = table( ...
    (1:numel(ledPositions)).', ...
    imageNames, ...
    [ledPositions.ledRow].', ...
    [ledPositions.ledCol].', ...
    [ledPositions.x].', ...
    [ledPositions.y].', ...
    [ledPositions.illuminationNaX].', ...
    [ledPositions.illuminationNaY].', ...
    [ledPositions.illuminationNa].', ...
    [ledPositions.shiftX].', ...
    [ledPositions.shiftY].', ...
    repmat(config.piControl.exposureMs, numel(ledPositions), 1), ...
    repmat(config.piControl.settleMs, numel(ledPositions), 1), ...
    repmat(config.piControl.iso, numel(ledPositions), 1), ...
    captureUrls, ...
    'VariableNames', { ...
        'capture_index', ...
        'image_name', ...
        'led_row', ...
        'led_col', ...
        'led_x_m', ...
        'led_y_m', ...
        'illumination_na_x', ...
        'illumination_na_y', ...
        'illumination_na', ...
        'shift_x_px', ...
        'shift_y_px', ...
        'exposure_ms', ...
        'settle_ms', ...
        'iso', ...
        'capture_url'});
end
